//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.GPMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GPMSEntities : DbContext
    {
        public GPMSEntities()
            : base("name=GPMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppActionGroup> AppActionGroups { get; set; }
        public virtual DbSet<AppActionGroupAccess> AppActionGroupAccesses { get; set; }
        public virtual DbSet<AppFormAction> AppFormActions { get; set; }
        public virtual DbSet<AppMenu> AppMenus { get; set; }
        public virtual DbSet<AppMenuGroup> AppMenuGroups { get; set; }
        public virtual DbSet<AppMenuGroupAccess> AppMenuGroupAccesses { get; set; }
        public virtual DbSet<AppUserCompanyAccess> AppUserCompanyAccesses { get; set; }
        public virtual DbSet<CartonInfo> CartonInfoes { get; set; }
        public virtual DbSet<ColorInfo> ColorInfoes { get; set; }
        public virtual DbSet<CompanyInfo> CompanyInfoes { get; set; }
        public virtual DbSet<CustomerInfo> CustomerInfoes { get; set; }
        public virtual DbSet<Log4AppActivity> Log4AppActivity { get; set; }
        public virtual DbSet<Log4UserActivity> Log4UserActivity { get; set; }
        public virtual DbSet<PackingType> PackingTypes { get; set; }
        public virtual DbSet<PaymentModeInfo> PaymentModeInfoes { get; set; }
        public virtual DbSet<POFrom> POFroms { get; set; }
        public virtual DbSet<POLevel> POLevels { get; set; }
        public virtual DbSet<POType> POTypes { get; set; }
        public virtual DbSet<ShipmentTerm> ShipmentTerms { get; set; }
        public virtual DbSet<ShippingMethod> ShippingMethods { get; set; }
        public virtual DbSet<StyleInfo> StyleInfoes { get; set; }
        public virtual DbSet<TermInfo> TermInfoes { get; set; }
        public virtual DbSet<UOM> UOMs { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<Log4DBActivity> Log4DBActivity { get; set; }
        public virtual DbSet<POApprovalStatu> POApprovalStatus { get; set; }
        public virtual DbSet<POD> PODs { get; set; }
        public virtual DbSet<POM> POMs { get; set; }
        public virtual DbSet<SizeInfo> SizeInfoes { get; set; }
        public virtual DbSet<PackingPlanData> PackingPlanDatas { get; set; }
        public virtual DbSet<POSizeD> POSizeDs { get; set; }
        public virtual DbSet<PackingInstructionD> PackingInstructionDs { get; set; }
        public virtual DbSet<PackingInstructionM> PackingInstructionMs { get; set; }
    
        public virtual ObjectResult<GetLabels_AcdSprt_Result> GetLabels_AcdSprt(Nullable<int> pCustomerID, string pPONo, Nullable<System.DateTime> pCreatedDate, ObjectParameter pActivityInfo, ObjectParameter pIsSucceeded)
        {
            var pCustomerIDParameter = pCustomerID.HasValue ?
                new ObjectParameter("pCustomerID", pCustomerID) :
                new ObjectParameter("pCustomerID", typeof(int));
    
            var pPONoParameter = pPONo != null ?
                new ObjectParameter("pPONo", pPONo) :
                new ObjectParameter("pPONo", typeof(string));
    
            var pCreatedDateParameter = pCreatedDate.HasValue ?
                new ObjectParameter("pCreatedDate", pCreatedDate) :
                new ObjectParameter("pCreatedDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLabels_AcdSprt_Result>("GetLabels_AcdSprt", pCustomerIDParameter, pPONoParameter, pCreatedDateParameter, pActivityInfo, pIsSucceeded);
        }
    
        public virtual ObjectResult<GetPackQty_Result> GetPackQty(Nullable<int> pCustomerID, string pPONo, Nullable<System.DateTime> pCreatedDate, ObjectParameter pActivityInfo, ObjectParameter pIsSucceeded)
        {
            var pCustomerIDParameter = pCustomerID.HasValue ?
                new ObjectParameter("pCustomerID", pCustomerID) :
                new ObjectParameter("pCustomerID", typeof(int));
    
            var pPONoParameter = pPONo != null ?
                new ObjectParameter("pPONo", pPONo) :
                new ObjectParameter("pPONo", typeof(string));
    
            var pCreatedDateParameter = pCreatedDate.HasValue ?
                new ObjectParameter("pCreatedDate", pCreatedDate) :
                new ObjectParameter("pCreatedDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPackQty_Result>("GetPackQty", pCustomerIDParameter, pPONoParameter, pCreatedDateParameter, pActivityInfo, pIsSucceeded);
        }
    
        public virtual int proc_GeneratePackingLabel(Nullable<int> pCustomerID, Nullable<int> startID, Nullable<int> endID, ObjectParameter activityInfo, ObjectParameter isSucceeded)
        {
            var pCustomerIDParameter = pCustomerID.HasValue ?
                new ObjectParameter("pCustomerID", pCustomerID) :
                new ObjectParameter("pCustomerID", typeof(int));
    
            var startIDParameter = startID.HasValue ?
                new ObjectParameter("startID", startID) :
                new ObjectParameter("startID", typeof(int));
    
            var endIDParameter = endID.HasValue ?
                new ObjectParameter("endID", endID) :
                new ObjectParameter("endID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_GeneratePackingLabel", pCustomerIDParameter, startIDParameter, endIDParameter, activityInfo, isSucceeded);
        }
    }
}
