//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.GPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log4UserActivity
    {
        public int Id { get; set; }
        public Nullable<int> ActionByUserId { get; set; }
        public string Action { get; set; }
        public string UserIpAddress { get; set; }
        public string BrowserName { get; set; }
        public string MachineName { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
