//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.GPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log4DBActivity
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string ExecutedUser { get; set; }
        public string ExecutionTime { get; set; }
        public Nullable<int> ObjectId { get; set; }
        public string ObjectName { get; set; }
        public string ObjectType { get; set; }
        public Nullable<int> ErrorNo { get; set; }
        public Nullable<int> ErrorSeverity { get; set; }
        public Nullable<int> ErrorState { get; set; }
        public Nullable<int> ErrorLine { get; set; }
        public string ErrorMessage { get; set; }
        public string AdditionalInfo { get; set; }
    }
}
