//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.GPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackingPlanData
    {
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string SourceFileName { get; set; }
        public string PONo { get; set; }
        public Nullable<int> GroupNo { get; set; }
        public Nullable<int> GroupCaseQty { get; set; }
        public Nullable<int> ItemQtyPerCase { get; set; }
        public string ItemNo { get; set; }
        public string StoreNo { get; set; }
        public string DC { get; set; }
        public string UccPartners { get; set; }
        public string UccType { get; set; }
        public string UccCoo { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> UpdatedByID { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> UpdatedCount { get; set; }
        public string Notes { get; set; }
    }
}
