//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP.GPMS.GPMSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GPMSService.IGPMSService")]
    public interface IGPMSService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddPackingInstructionD", ReplyAction="http://tempuri.org/IGPMSService/AddPackingInstructionDResponse")]
        Entities.GPMS.PackingDto AddPackingInstructionD(Entities.GPMS.PackingInstructionDBo packingInstructionDBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddPackingInstructionD", ReplyAction="http://tempuri.org/IGPMSService/AddPackingInstructionDResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.PackingDto> AddPackingInstructionDAsync(Entities.GPMS.PackingInstructionDBo packingInstructionDBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetLabels_AcdSprt", ReplyAction="http://tempuri.org/IGPMSService/GetLabels_AcdSprtResponse")]
        Entities.GPMS.PackingDto GetLabels_AcdSprt(System.Nullable<int> pCustomerID, string pPONo, System.Nullable<System.DateTime> pCreatedDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetLabels_AcdSprt", ReplyAction="http://tempuri.org/IGPMSService/GetLabels_AcdSprtResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.PackingDto> GetLabels_AcdSprtAsync(System.Nullable<int> pCustomerID, string pPONo, System.Nullable<System.DateTime> pCreatedDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPackQty", ReplyAction="http://tempuri.org/IGPMSService/GetPackQtyResponse")]
        Entities.GPMS.PackingDto GetPackQty(System.Nullable<int> pCustomerID, string pPONo, System.Nullable<System.DateTime> pCreatedDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPackQty", ReplyAction="http://tempuri.org/IGPMSService/GetPackQtyResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.PackingDto> GetPackQtyAsync(System.Nullable<int> pCustomerID, string pPONo, System.Nullable<System.DateTime> pCreatedDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/SkipNGetN_OfCustomerDataWithSearch", ReplyAction="http://tempuri.org/IGPMSService/SkipNGetN_OfCustomerDataWithSearchResponse")]
        Entities.GPMS.FetchDto SkipNGetN_OfCustomerDataWithSearch(int pCompanyID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/SkipNGetN_OfCustomerDataWithSearch", ReplyAction="http://tempuri.org/IGPMSService/SkipNGetN_OfCustomerDataWithSearchResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.FetchDto> SkipNGetN_OfCustomerDataWithSearchAsync(int pCompanyID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/SkipNGetN_OfStyleDataWithSearch", ReplyAction="http://tempuri.org/IGPMSService/SkipNGetN_OfStyleDataWithSearchResponse")]
        Entities.GPMS.FetchDto SkipNGetN_OfStyleDataWithSearch(int pCustomerID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/SkipNGetN_OfStyleDataWithSearch", ReplyAction="http://tempuri.org/IGPMSService/SkipNGetN_OfStyleDataWithSearchResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.FetchDto> SkipNGetN_OfStyleDataWithSearchAsync(int pCustomerID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/SkipNGetN_OfSizeDataWithSearch", ReplyAction="http://tempuri.org/IGPMSService/SkipNGetN_OfSizeDataWithSearchResponse")]
        Entities.GPMS.FetchDto SkipNGetN_OfSizeDataWithSearch(System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/SkipNGetN_OfSizeDataWithSearch", ReplyAction="http://tempuri.org/IGPMSService/SkipNGetN_OfSizeDataWithSearchResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.FetchDto> SkipNGetN_OfSizeDataWithSearchAsync(System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/SkipNGetN_OfColorDataWithSearch", ReplyAction="http://tempuri.org/IGPMSService/SkipNGetN_OfColorDataWithSearchResponse")]
        Entities.GPMS.FetchDto SkipNGetN_OfColorDataWithSearch(int pCustomerID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/SkipNGetN_OfColorDataWithSearch", ReplyAction="http://tempuri.org/IGPMSService/SkipNGetN_OfColorDataWithSearchResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.FetchDto> SkipNGetN_OfColorDataWithSearchAsync(int pCustomerID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddCarton", ReplyAction="http://tempuri.org/IGPMSService/AddCartonResponse")]
        Entities.GPMS.CatalogDto AddCarton(Entities.GPMS.CartonInfoBo pCartonInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddCarton", ReplyAction="http://tempuri.org/IGPMSService/AddCartonResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> AddCartonAsync(Entities.GPMS.CartonInfoBo pCartonInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/UpdateCarton", ReplyAction="http://tempuri.org/IGPMSService/UpdateCartonResponse")]
        Entities.GPMS.CatalogDto UpdateCarton(Entities.GPMS.CartonInfoBo pCartonInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/UpdateCarton", ReplyAction="http://tempuri.org/IGPMSService/UpdateCartonResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> UpdateCartonAsync(Entities.GPMS.CartonInfoBo pCartonInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetCartonById", ReplyAction="http://tempuri.org/IGPMSService/GetCartonByIdResponse")]
        Entities.GPMS.CatalogDto GetCartonById(int pCartonId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetCartonById", ReplyAction="http://tempuri.org/IGPMSService/GetCartonByIdResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetCartonByIdAsync(int pCartonId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetCartonByCode", ReplyAction="http://tempuri.org/IGPMSService/GetCartonByCodeResponse")]
        Entities.GPMS.CatalogDto GetCartonByCode(string pCartonCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetCartonByCode", ReplyAction="http://tempuri.org/IGPMSService/GetCartonByCodeResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetCartonByCodeAsync(string pCartonCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetAllCartons", ReplyAction="http://tempuri.org/IGPMSService/GetAllCartonsResponse")]
        Entities.GPMS.CatalogDto GetAllCartons(System.Nullable<bool> pIsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetAllCartons", ReplyAction="http://tempuri.org/IGPMSService/GetAllCartonsResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetAllCartonsAsync(System.Nullable<bool> pIsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddColor", ReplyAction="http://tempuri.org/IGPMSService/AddColorResponse")]
        Entities.GPMS.CatalogDto AddColor(Entities.GPMS.ColorInfoBo pColorInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddColor", ReplyAction="http://tempuri.org/IGPMSService/AddColorResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> AddColorAsync(Entities.GPMS.ColorInfoBo pColorInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/UpdateColor", ReplyAction="http://tempuri.org/IGPMSService/UpdateColorResponse")]
        Entities.GPMS.CatalogDto UpdateColor(Entities.GPMS.ColorInfoBo pColorInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/UpdateColor", ReplyAction="http://tempuri.org/IGPMSService/UpdateColorResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> UpdateColorAsync(Entities.GPMS.ColorInfoBo pColorInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetColorById", ReplyAction="http://tempuri.org/IGPMSService/GetColorByIdResponse")]
        Entities.GPMS.CatalogDto GetColorById(int pColorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetColorById", ReplyAction="http://tempuri.org/IGPMSService/GetColorByIdResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetColorByIdAsync(int pColorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetColorByCode", ReplyAction="http://tempuri.org/IGPMSService/GetColorByCodeResponse")]
        Entities.GPMS.CatalogDto GetColorByCode(string pColorCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetColorByCode", ReplyAction="http://tempuri.org/IGPMSService/GetColorByCodeResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetColorByCodeAsync(string pColorCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetAllColors", ReplyAction="http://tempuri.org/IGPMSService/GetAllColorsResponse")]
        Entities.GPMS.CatalogDto GetAllColors(System.Nullable<bool> pIsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetAllColors", ReplyAction="http://tempuri.org/IGPMSService/GetAllColorsResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetAllColorsAsync(System.Nullable<bool> pIsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddCustomer", ReplyAction="http://tempuri.org/IGPMSService/AddCustomerResponse")]
        Entities.GPMS.CatalogDto AddCustomer(Entities.GPMS.CustomerInfoBo pCustomerInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddCustomer", ReplyAction="http://tempuri.org/IGPMSService/AddCustomerResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> AddCustomerAsync(Entities.GPMS.CustomerInfoBo pCustomerInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/UpdateCustomer", ReplyAction="http://tempuri.org/IGPMSService/UpdateCustomerResponse")]
        Entities.GPMS.CatalogDto UpdateCustomer(Entities.GPMS.CustomerInfoBo pCustomerInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/UpdateCustomer", ReplyAction="http://tempuri.org/IGPMSService/UpdateCustomerResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> UpdateCustomerAsync(Entities.GPMS.CustomerInfoBo pCustomerInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetCustomerById", ReplyAction="http://tempuri.org/IGPMSService/GetCustomerByIdResponse")]
        Entities.GPMS.CatalogDto GetCustomerById(int pCustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetCustomerById", ReplyAction="http://tempuri.org/IGPMSService/GetCustomerByIdResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetCustomerByIdAsync(int pCustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetCustomerByCode", ReplyAction="http://tempuri.org/IGPMSService/GetCustomerByCodeResponse")]
        Entities.GPMS.CatalogDto GetCustomerByCode(string pCustomerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetCustomerByCode", ReplyAction="http://tempuri.org/IGPMSService/GetCustomerByCodeResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetCustomerByCodeAsync(string pCustomerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetAllCustomers", ReplyAction="http://tempuri.org/IGPMSService/GetAllCustomersResponse")]
        Entities.GPMS.CatalogDto GetAllCustomers(System.Nullable<bool> pIsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetAllCustomers", ReplyAction="http://tempuri.org/IGPMSService/GetAllCustomersResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetAllCustomersAsync(System.Nullable<bool> pIsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddPaymentMode", ReplyAction="http://tempuri.org/IGPMSService/AddPaymentModeResponse")]
        Entities.GPMS.CatalogDto AddPaymentMode(Entities.GPMS.PaymentModeInfoBo pPaymentModeInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddPaymentMode", ReplyAction="http://tempuri.org/IGPMSService/AddPaymentModeResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> AddPaymentModeAsync(Entities.GPMS.PaymentModeInfoBo pPaymentModeInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/UpdatePaymentMode", ReplyAction="http://tempuri.org/IGPMSService/UpdatePaymentModeResponse")]
        Entities.GPMS.CatalogDto UpdatePaymentMode(Entities.GPMS.PaymentModeInfoBo pPaymentModeInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/UpdatePaymentMode", ReplyAction="http://tempuri.org/IGPMSService/UpdatePaymentModeResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> UpdatePaymentModeAsync(Entities.GPMS.PaymentModeInfoBo pPaymentModeInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPaymentModeById", ReplyAction="http://tempuri.org/IGPMSService/GetPaymentModeByIdResponse")]
        Entities.GPMS.CatalogDto GetPaymentModeById(int pPaymentModeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPaymentModeById", ReplyAction="http://tempuri.org/IGPMSService/GetPaymentModeByIdResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetPaymentModeByIdAsync(int pPaymentModeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPaymentModeByCode", ReplyAction="http://tempuri.org/IGPMSService/GetPaymentModeByCodeResponse")]
        Entities.GPMS.CatalogDto GetPaymentModeByCode(string pPaymentModeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPaymentModeByCode", ReplyAction="http://tempuri.org/IGPMSService/GetPaymentModeByCodeResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetPaymentModeByCodeAsync(string pPaymentModeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetAllPaymentModes", ReplyAction="http://tempuri.org/IGPMSService/GetAllPaymentModesResponse")]
        Entities.GPMS.CatalogDto GetAllPaymentModes(System.Nullable<bool> pIsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetAllPaymentModes", ReplyAction="http://tempuri.org/IGPMSService/GetAllPaymentModesResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetAllPaymentModesAsync(System.Nullable<bool> pIsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddSize", ReplyAction="http://tempuri.org/IGPMSService/AddSizeResponse")]
        Entities.GPMS.CatalogDto AddSize(Entities.GPMS.SizeInfoBo pSizeInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddSize", ReplyAction="http://tempuri.org/IGPMSService/AddSizeResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> AddSizeAsync(Entities.GPMS.SizeInfoBo pSizeInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/UpdateSize", ReplyAction="http://tempuri.org/IGPMSService/UpdateSizeResponse")]
        Entities.GPMS.CatalogDto UpdateSize(Entities.GPMS.SizeInfoBo pSizeInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/UpdateSize", ReplyAction="http://tempuri.org/IGPMSService/UpdateSizeResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> UpdateSizeAsync(Entities.GPMS.SizeInfoBo pSizeInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetSizeById", ReplyAction="http://tempuri.org/IGPMSService/GetSizeByIdResponse")]
        Entities.GPMS.CatalogDto GetSizeById(int pSizeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetSizeById", ReplyAction="http://tempuri.org/IGPMSService/GetSizeByIdResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetSizeByIdAsync(int pSizeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetSizeByCode", ReplyAction="http://tempuri.org/IGPMSService/GetSizeByCodeResponse")]
        Entities.GPMS.CatalogDto GetSizeByCode(string pSizeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetSizeByCode", ReplyAction="http://tempuri.org/IGPMSService/GetSizeByCodeResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetSizeByCodeAsync(string pSizeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetAllSizes", ReplyAction="http://tempuri.org/IGPMSService/GetAllSizesResponse")]
        Entities.GPMS.CatalogDto GetAllSizes(System.Nullable<bool> pIsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetAllSizes", ReplyAction="http://tempuri.org/IGPMSService/GetAllSizesResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetAllSizesAsync(System.Nullable<bool> pIsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddStyle", ReplyAction="http://tempuri.org/IGPMSService/AddStyleResponse")]
        Entities.GPMS.CatalogDto AddStyle(Entities.GPMS.StyleInfoBo pStyleInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddStyle", ReplyAction="http://tempuri.org/IGPMSService/AddStyleResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> AddStyleAsync(Entities.GPMS.StyleInfoBo pStyleInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/UpdateStyle", ReplyAction="http://tempuri.org/IGPMSService/UpdateStyleResponse")]
        Entities.GPMS.CatalogDto UpdateStyle(Entities.GPMS.StyleInfoBo pStyleInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/UpdateStyle", ReplyAction="http://tempuri.org/IGPMSService/UpdateStyleResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> UpdateStyleAsync(Entities.GPMS.StyleInfoBo pStyleInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetStyleById", ReplyAction="http://tempuri.org/IGPMSService/GetStyleByIdResponse")]
        Entities.GPMS.CatalogDto GetStyleById(int pStyleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetStyleById", ReplyAction="http://tempuri.org/IGPMSService/GetStyleByIdResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetStyleByIdAsync(int pStyleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetStyleByCode", ReplyAction="http://tempuri.org/IGPMSService/GetStyleByCodeResponse")]
        Entities.GPMS.CatalogDto GetStyleByCode(string pStyleCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetStyleByCode", ReplyAction="http://tempuri.org/IGPMSService/GetStyleByCodeResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetStyleByCodeAsync(string pStyleCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetAllStyles", ReplyAction="http://tempuri.org/IGPMSService/GetAllStylesResponse")]
        Entities.GPMS.CatalogDto GetAllStyles(System.Nullable<bool> pIsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetAllStyles", ReplyAction="http://tempuri.org/IGPMSService/GetAllStylesResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetAllStylesAsync(System.Nullable<bool> pIsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddTerm", ReplyAction="http://tempuri.org/IGPMSService/AddTermResponse")]
        Entities.GPMS.CatalogDto AddTerm(Entities.GPMS.TermInfoBo pTermInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddTerm", ReplyAction="http://tempuri.org/IGPMSService/AddTermResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> AddTermAsync(Entities.GPMS.TermInfoBo pTermInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/UpdateTerm", ReplyAction="http://tempuri.org/IGPMSService/UpdateTermResponse")]
        Entities.GPMS.CatalogDto UpdateTerm(Entities.GPMS.TermInfoBo pTermInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/UpdateTerm", ReplyAction="http://tempuri.org/IGPMSService/UpdateTermResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> UpdateTermAsync(Entities.GPMS.TermInfoBo pTermInfoBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetTermById", ReplyAction="http://tempuri.org/IGPMSService/GetTermByIdResponse")]
        Entities.GPMS.CatalogDto GetTermById(int pTermId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetTermById", ReplyAction="http://tempuri.org/IGPMSService/GetTermByIdResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetTermByIdAsync(int pTermId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetTermByCode", ReplyAction="http://tempuri.org/IGPMSService/GetTermByCodeResponse")]
        Entities.GPMS.CatalogDto GetTermByCode(string pTermCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetTermByCode", ReplyAction="http://tempuri.org/IGPMSService/GetTermByCodeResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetTermByCodeAsync(string pTermCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetAllTerms", ReplyAction="http://tempuri.org/IGPMSService/GetAllTermsResponse")]
        Entities.GPMS.CatalogDto GetAllTerms(System.Nullable<bool> pIsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetAllTerms", ReplyAction="http://tempuri.org/IGPMSService/GetAllTermsResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetAllTermsAsync(System.Nullable<bool> pIsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPOTypeById", ReplyAction="http://tempuri.org/IGPMSService/GetPOTypeByIdResponse")]
        Entities.GPMS.CatalogDto GetPOTypeById(int pPOTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPOTypeById", ReplyAction="http://tempuri.org/IGPMSService/GetPOTypeByIdResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetPOTypeByIdAsync(int pPOTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPOTypeByCode", ReplyAction="http://tempuri.org/IGPMSService/GetPOTypeByCodeResponse")]
        Entities.GPMS.CatalogDto GetPOTypeByCode(string pPOTypeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPOTypeByCode", ReplyAction="http://tempuri.org/IGPMSService/GetPOTypeByCodeResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetPOTypeByCodeAsync(string pPOTypeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetAllPOTypes", ReplyAction="http://tempuri.org/IGPMSService/GetAllPOTypesResponse")]
        Entities.GPMS.CatalogDto GetAllPOTypes(System.Nullable<bool> pIsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetAllPOTypes", ReplyAction="http://tempuri.org/IGPMSService/GetAllPOTypesResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetAllPOTypesAsync(System.Nullable<bool> pIsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPOLevelById", ReplyAction="http://tempuri.org/IGPMSService/GetPOLevelByIdResponse")]
        Entities.GPMS.CatalogDto GetPOLevelById(int pPOLevelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPOLevelById", ReplyAction="http://tempuri.org/IGPMSService/GetPOLevelByIdResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetPOLevelByIdAsync(int pPOLevelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPOLevelByCode", ReplyAction="http://tempuri.org/IGPMSService/GetPOLevelByCodeResponse")]
        Entities.GPMS.CatalogDto GetPOLevelByCode(string pPOLevelCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPOLevelByCode", ReplyAction="http://tempuri.org/IGPMSService/GetPOLevelByCodeResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetPOLevelByCodeAsync(string pPOLevelCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetAllPOLevels", ReplyAction="http://tempuri.org/IGPMSService/GetAllPOLevelsResponse")]
        Entities.GPMS.CatalogDto GetAllPOLevels(System.Nullable<bool> pIsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetAllPOLevels", ReplyAction="http://tempuri.org/IGPMSService/GetAllPOLevelsResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetAllPOLevelsAsync(System.Nullable<bool> pIsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPOFromById", ReplyAction="http://tempuri.org/IGPMSService/GetPOFromByIdResponse")]
        Entities.GPMS.CatalogDto GetPOFromById(int pPOFromId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPOFromById", ReplyAction="http://tempuri.org/IGPMSService/GetPOFromByIdResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetPOFromByIdAsync(int pPOFromId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPOFromByCode", ReplyAction="http://tempuri.org/IGPMSService/GetPOFromByCodeResponse")]
        Entities.GPMS.CatalogDto GetPOFromByCode(string pPOFromCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPOFromByCode", ReplyAction="http://tempuri.org/IGPMSService/GetPOFromByCodeResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetPOFromByCodeAsync(string pPOFromCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetAllPOFroms", ReplyAction="http://tempuri.org/IGPMSService/GetAllPOFromsResponse")]
        Entities.GPMS.CatalogDto GetAllPOFroms(System.Nullable<bool> pIsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetAllPOFroms", ReplyAction="http://tempuri.org/IGPMSService/GetAllPOFromsResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetAllPOFromsAsync(System.Nullable<bool> pIsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPackingTypeById", ReplyAction="http://tempuri.org/IGPMSService/GetPackingTypeByIdResponse")]
        Entities.GPMS.CatalogDto GetPackingTypeById(int pPackingTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPackingTypeById", ReplyAction="http://tempuri.org/IGPMSService/GetPackingTypeByIdResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetPackingTypeByIdAsync(int pPackingTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPackingTypeByCode", ReplyAction="http://tempuri.org/IGPMSService/GetPackingTypeByCodeResponse")]
        Entities.GPMS.CatalogDto GetPackingTypeByCode(string pPackingTypeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPackingTypeByCode", ReplyAction="http://tempuri.org/IGPMSService/GetPackingTypeByCodeResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetPackingTypeByCodeAsync(string pPackingTypeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetAllPackingTypes", ReplyAction="http://tempuri.org/IGPMSService/GetAllPackingTypesResponse")]
        Entities.GPMS.CatalogDto GetAllPackingTypes(System.Nullable<bool> pIsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetAllPackingTypes", ReplyAction="http://tempuri.org/IGPMSService/GetAllPackingTypesResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetAllPackingTypesAsync(System.Nullable<bool> pIsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetShipmentTermById", ReplyAction="http://tempuri.org/IGPMSService/GetShipmentTermByIdResponse")]
        Entities.GPMS.CatalogDto GetShipmentTermById(int pShipmentTermId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetShipmentTermById", ReplyAction="http://tempuri.org/IGPMSService/GetShipmentTermByIdResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetShipmentTermByIdAsync(int pShipmentTermId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetShipmentTermByCode", ReplyAction="http://tempuri.org/IGPMSService/GetShipmentTermByCodeResponse")]
        Entities.GPMS.CatalogDto GetShipmentTermByCode(string pShipmentTermCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetShipmentTermByCode", ReplyAction="http://tempuri.org/IGPMSService/GetShipmentTermByCodeResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetShipmentTermByCodeAsync(string pShipmentTermCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetAllShipmentTerms", ReplyAction="http://tempuri.org/IGPMSService/GetAllShipmentTermsResponse")]
        Entities.GPMS.CatalogDto GetAllShipmentTerms(System.Nullable<bool> pIsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetAllShipmentTerms", ReplyAction="http://tempuri.org/IGPMSService/GetAllShipmentTermsResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetAllShipmentTermsAsync(System.Nullable<bool> pIsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/UpdateShippingMethod", ReplyAction="http://tempuri.org/IGPMSService/UpdateShippingMethodResponse")]
        Entities.GPMS.CatalogDto UpdateShippingMethod(Entities.GPMS.ShippingMethodBo pShippingMethodBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/UpdateShippingMethod", ReplyAction="http://tempuri.org/IGPMSService/UpdateShippingMethodResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> UpdateShippingMethodAsync(Entities.GPMS.ShippingMethodBo pShippingMethodBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetShippingMethodById", ReplyAction="http://tempuri.org/IGPMSService/GetShippingMethodByIdResponse")]
        Entities.GPMS.CatalogDto GetShippingMethodById(int pShippingMethodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetShippingMethodById", ReplyAction="http://tempuri.org/IGPMSService/GetShippingMethodByIdResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetShippingMethodByIdAsync(int pShippingMethodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetShippingMethodByCode", ReplyAction="http://tempuri.org/IGPMSService/GetShippingMethodByCodeResponse")]
        Entities.GPMS.CatalogDto GetShippingMethodByCode(string pShippingMethodCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetShippingMethodByCode", ReplyAction="http://tempuri.org/IGPMSService/GetShippingMethodByCodeResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetShippingMethodByCodeAsync(string pShippingMethodCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetAllShippingMethods", ReplyAction="http://tempuri.org/IGPMSService/GetAllShippingMethodsResponse")]
        Entities.GPMS.CatalogDto GetAllShippingMethods(System.Nullable<bool> pIsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetAllShippingMethods", ReplyAction="http://tempuri.org/IGPMSService/GetAllShippingMethodsResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetAllShippingMethodsAsync(System.Nullable<bool> pIsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddPOM", ReplyAction="http://tempuri.org/IGPMSService/AddPOMResponse")]
        Entities.GPMS.OrderDto AddPOM(Entities.GPMS.POMBo POMBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddPOM", ReplyAction="http://tempuri.org/IGPMSService/AddPOMResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.OrderDto> AddPOMAsync(Entities.GPMS.POMBo POMBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/UpdatePOM", ReplyAction="http://tempuri.org/IGPMSService/UpdatePOMResponse")]
        Entities.GPMS.OrderDto UpdatePOM(Entities.GPMS.POMBo POMBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/UpdatePOM", ReplyAction="http://tempuri.org/IGPMSService/UpdatePOMResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.OrderDto> UpdatePOMAsync(Entities.GPMS.POMBo POMBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPOMById", ReplyAction="http://tempuri.org/IGPMSService/GetPOMByIdResponse")]
        Entities.GPMS.OrderDto GetPOMById(int pPOMId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPOMById", ReplyAction="http://tempuri.org/IGPMSService/GetPOMByIdResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.OrderDto> GetPOMByIdAsync(int pPOMId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPOByPONo", ReplyAction="http://tempuri.org/IGPMSService/GetPOByPONoResponse")]
        Entities.GPMS.OrderDto GetPOByPONo(string pPONo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPOByPONo", ReplyAction="http://tempuri.org/IGPMSService/GetPOByPONoResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.OrderDto> GetPOByPONoAsync(string pPONo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/DeletePOM", ReplyAction="http://tempuri.org/IGPMSService/DeletePOMResponse")]
        Entities.GPMS.OrderDto DeletePOM(int Id, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/DeletePOM", ReplyAction="http://tempuri.org/IGPMSService/DeletePOMResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.OrderDto> DeletePOMAsync(int Id, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/UpdatePOApprovedStatus", ReplyAction="http://tempuri.org/IGPMSService/UpdatePOApprovedStatusResponse")]
        Entities.GPMS.OrderDto UpdatePOApprovedStatus(Entities.GPMS.POApprovalStatusBo POApprovalStatuBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/UpdatePOApprovedStatus", ReplyAction="http://tempuri.org/IGPMSService/UpdatePOApprovedStatusResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.OrderDto> UpdatePOApprovedStatusAsync(Entities.GPMS.POApprovalStatusBo POApprovalStatuBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/IsPONumberExist", ReplyAction="http://tempuri.org/IGPMSService/IsPONumberExistResponse")]
        Entities.GPMS.ValidationDto IsPONumberExist(string pPoNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/IsPONumberExist", ReplyAction="http://tempuri.org/IGPMSService/IsPONumberExistResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.ValidationDto> IsPONumberExistAsync(string pPoNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddPOD", ReplyAction="http://tempuri.org/IGPMSService/AddPODResponse")]
        Entities.GPMS.OrderDto AddPOD(Entities.GPMS.PODBo[] PODBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddPOD", ReplyAction="http://tempuri.org/IGPMSService/AddPODResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.OrderDto> AddPODAsync(Entities.GPMS.PODBo[] PODBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/UpdatePOD", ReplyAction="http://tempuri.org/IGPMSService/UpdatePODResponse")]
        Entities.GPMS.OrderDto UpdatePOD(Entities.GPMS.PODBo PODBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/UpdatePOD", ReplyAction="http://tempuri.org/IGPMSService/UpdatePODResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.OrderDto> UpdatePODAsync(Entities.GPMS.PODBo PODBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddUpdatePOD", ReplyAction="http://tempuri.org/IGPMSService/AddUpdatePODResponse")]
        Entities.GPMS.OrderDto AddUpdatePOD(Entities.GPMS.PODBo[] PODBoList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddUpdatePOD", ReplyAction="http://tempuri.org/IGPMSService/AddUpdatePODResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.OrderDto> AddUpdatePODAsync(Entities.GPMS.PODBo[] PODBoList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPODById", ReplyAction="http://tempuri.org/IGPMSService/GetPODByIdResponse")]
        Entities.GPMS.OrderDto GetPODById(int pPODId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPODById", ReplyAction="http://tempuri.org/IGPMSService/GetPODByIdResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.OrderDto> GetPODByIdAsync(int pPODId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/DeletePOD", ReplyAction="http://tempuri.org/IGPMSService/DeletePODResponse")]
        Entities.GPMS.OrderDto DeletePOD(int Id, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/DeletePOD", ReplyAction="http://tempuri.org/IGPMSService/DeletePODResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.OrderDto> DeletePODAsync(int Id, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddPOSizeD", ReplyAction="http://tempuri.org/IGPMSService/AddPOSizeDResponse")]
        Entities.GPMS.OrderDto AddPOSizeD(Entities.GPMS.POSizeDBo[] POSizeDBoList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddPOSizeD", ReplyAction="http://tempuri.org/IGPMSService/AddPOSizeDResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.OrderDto> AddPOSizeDAsync(Entities.GPMS.POSizeDBo[] POSizeDBoList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/UpdatePOSizeD", ReplyAction="http://tempuri.org/IGPMSService/UpdatePOSizeDResponse")]
        Entities.GPMS.OrderDto UpdatePOSizeD(Entities.GPMS.POSizeDBo POSizeDBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/UpdatePOSizeD", ReplyAction="http://tempuri.org/IGPMSService/UpdatePOSizeDResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.OrderDto> UpdatePOSizeDAsync(Entities.GPMS.POSizeDBo POSizeDBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPOSizeDById", ReplyAction="http://tempuri.org/IGPMSService/GetPOSizeDByIdResponse")]
        Entities.GPMS.OrderDto GetPOSizeDById(int pPOSizeDId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetPOSizeDById", ReplyAction="http://tempuri.org/IGPMSService/GetPOSizeDByIdResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.OrderDto> GetPOSizeDByIdAsync(int pPOSizeDId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddUpdatePOSizeD", ReplyAction="http://tempuri.org/IGPMSService/AddUpdatePOSizeDResponse")]
        Entities.GPMS.OrderDto AddUpdatePOSizeD(Entities.GPMS.POSizeDBo[] POSizeDBoList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddUpdatePOSizeD", ReplyAction="http://tempuri.org/IGPMSService/AddUpdatePOSizeDResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.OrderDto> AddUpdatePOSizeDAsync(Entities.GPMS.POSizeDBo[] POSizeDBoList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/DeletePOSizeD", ReplyAction="http://tempuri.org/IGPMSService/DeletePOSizeDResponse")]
        Entities.GPMS.OrderDto DeletePOSizeD(int Id, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/DeletePOSizeD", ReplyAction="http://tempuri.org/IGPMSService/DeletePOSizeDResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.OrderDto> DeletePOSizeDAsync(int Id, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/DeletePOSizeDCollection", ReplyAction="http://tempuri.org/IGPMSService/DeletePOSizeDCollectionResponse")]
        Entities.GPMS.OrderDto DeletePOSizeDCollection(int[] pPOSizeDIDs, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/DeletePOSizeDCollection", ReplyAction="http://tempuri.org/IGPMSService/DeletePOSizeDCollectionResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.OrderDto> DeletePOSizeDCollectionAsync(int[] pPOSizeDIDs, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/IsItemExistInPO", ReplyAction="http://tempuri.org/IGPMSService/IsItemExistInPOResponse")]
        Entities.GPMS.ValidationDto IsItemExistInPO(string PONo, string ItemNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/IsItemExistInPO", ReplyAction="http://tempuri.org/IGPMSService/IsItemExistInPOResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.ValidationDto> IsItemExistInPOAsync(string PONo, string ItemNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/IsPackQtyValid", ReplyAction="http://tempuri.org/IGPMSService/IsPackQtyValidResponse")]
        Entities.GPMS.ValidationDto IsPackQtyValid(int pCustomerID, string PONo, string ItemNo, int CurrentPackQty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/IsPackQtyValid", ReplyAction="http://tempuri.org/IGPMSService/IsPackQtyValidResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.ValidationDto> IsPackQtyValidAsync(int pCustomerID, string PONo, string ItemNo, int CurrentPackQty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetItemNo", ReplyAction="http://tempuri.org/IGPMSService/GetItemNoResponse")]
        Entities.GPMS.OrderDto GetItemNo(int pCustomerID, int pStyleID, int pColorID, int pSizeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetItemNo", ReplyAction="http://tempuri.org/IGPMSService/GetItemNoResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.OrderDto> GetItemNoAsync(int pCustomerID, int pStyleID, int pColorID, int pSizeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddPackingPlanData", ReplyAction="http://tempuri.org/IGPMSService/AddPackingPlanDataResponse")]
        Entities.GPMS.PackingDto AddPackingPlanData(Entities.GPMS.PackingDto PackingDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddPackingPlanData", ReplyAction="http://tempuri.org/IGPMSService/AddPackingPlanDataResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.PackingDto> AddPackingPlanDataAsync(Entities.GPMS.PackingDto PackingDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/IsPackingPlanAlreadyProcessed", ReplyAction="http://tempuri.org/IGPMSService/IsPackingPlanAlreadyProcessedResponse")]
        Entities.GPMS.ValidationDto IsPackingPlanAlreadyProcessed(string pFileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/IsPackingPlanAlreadyProcessed", ReplyAction="http://tempuri.org/IGPMSService/IsPackingPlanAlreadyProcessedResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.ValidationDto> IsPackingPlanAlreadyProcessedAsync(string pFileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddPackingInstructionM", ReplyAction="http://tempuri.org/IGPMSService/AddPackingInstructionMResponse")]
        Entities.GPMS.PackingDto AddPackingInstructionM(Entities.GPMS.PackingInstructionMBo packingInstructionMBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/AddPackingInstructionM", ReplyAction="http://tempuri.org/IGPMSService/AddPackingInstructionMResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.PackingDto> AddPackingInstructionMAsync(Entities.GPMS.PackingInstructionMBo packingInstructionMBo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetBoxDataByBarcode", ReplyAction="http://tempuri.org/IGPMSService/GetBoxDataByBarcodeResponse")]
        Entities.GPMS.PackingDto GetBoxDataByBarcode(string pBoxBacode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/GetBoxDataByBarcode", ReplyAction="http://tempuri.org/IGPMSService/GetBoxDataByBarcodeResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.PackingDto> GetBoxDataByBarcodeAsync(string pBoxBacode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/SaveBoxPacking", ReplyAction="http://tempuri.org/IGPMSService/SaveBoxPackingResponse")]
        Entities.GPMS.PackingDto SaveBoxPacking(int pPackingInstructionMID, int pUpdatedByID, string pUpdatedBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/SaveBoxPacking", ReplyAction="http://tempuri.org/IGPMSService/SaveBoxPackingResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.PackingDto> SaveBoxPackingAsync(int pPackingInstructionMID, int pUpdatedByID, string pUpdatedBy);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGPMSServiceChannel : APP.GPMS.GPMSService.IGPMSService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GPMSServiceClient : System.ServiceModel.ClientBase<APP.GPMS.GPMSService.IGPMSService>, APP.GPMS.GPMSService.IGPMSService {
        
        public GPMSServiceClient() {
        }
        
        public GPMSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GPMSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GPMSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GPMSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Entities.GPMS.PackingDto AddPackingInstructionD(Entities.GPMS.PackingInstructionDBo packingInstructionDBo) {
            return base.Channel.AddPackingInstructionD(packingInstructionDBo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.PackingDto> AddPackingInstructionDAsync(Entities.GPMS.PackingInstructionDBo packingInstructionDBo) {
            return base.Channel.AddPackingInstructionDAsync(packingInstructionDBo);
        }
        
        public Entities.GPMS.PackingDto GetLabels_AcdSprt(System.Nullable<int> pCustomerID, string pPONo, System.Nullable<System.DateTime> pCreatedDate) {
            return base.Channel.GetLabels_AcdSprt(pCustomerID, pPONo, pCreatedDate);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.PackingDto> GetLabels_AcdSprtAsync(System.Nullable<int> pCustomerID, string pPONo, System.Nullable<System.DateTime> pCreatedDate) {
            return base.Channel.GetLabels_AcdSprtAsync(pCustomerID, pPONo, pCreatedDate);
        }
        
        public Entities.GPMS.PackingDto GetPackQty(System.Nullable<int> pCustomerID, string pPONo, System.Nullable<System.DateTime> pCreatedDate) {
            return base.Channel.GetPackQty(pCustomerID, pPONo, pCreatedDate);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.PackingDto> GetPackQtyAsync(System.Nullable<int> pCustomerID, string pPONo, System.Nullable<System.DateTime> pCreatedDate) {
            return base.Channel.GetPackQtyAsync(pCustomerID, pPONo, pCreatedDate);
        }
        
        public Entities.GPMS.FetchDto SkipNGetN_OfCustomerDataWithSearch(int pCompanyID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo) {
            return base.Channel.SkipNGetN_OfCustomerDataWithSearch(pCompanyID, pIsActive, pSearchTxt, pSkipNo, pTakeNo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.FetchDto> SkipNGetN_OfCustomerDataWithSearchAsync(int pCompanyID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo) {
            return base.Channel.SkipNGetN_OfCustomerDataWithSearchAsync(pCompanyID, pIsActive, pSearchTxt, pSkipNo, pTakeNo);
        }
        
        public Entities.GPMS.FetchDto SkipNGetN_OfStyleDataWithSearch(int pCustomerID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo) {
            return base.Channel.SkipNGetN_OfStyleDataWithSearch(pCustomerID, pIsActive, pSearchTxt, pSkipNo, pTakeNo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.FetchDto> SkipNGetN_OfStyleDataWithSearchAsync(int pCustomerID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo) {
            return base.Channel.SkipNGetN_OfStyleDataWithSearchAsync(pCustomerID, pIsActive, pSearchTxt, pSkipNo, pTakeNo);
        }
        
        public Entities.GPMS.FetchDto SkipNGetN_OfSizeDataWithSearch(System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo) {
            return base.Channel.SkipNGetN_OfSizeDataWithSearch(pIsActive, pSearchTxt, pSkipNo, pTakeNo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.FetchDto> SkipNGetN_OfSizeDataWithSearchAsync(System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo) {
            return base.Channel.SkipNGetN_OfSizeDataWithSearchAsync(pIsActive, pSearchTxt, pSkipNo, pTakeNo);
        }
        
        public Entities.GPMS.FetchDto SkipNGetN_OfColorDataWithSearch(int pCustomerID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo) {
            return base.Channel.SkipNGetN_OfColorDataWithSearch(pCustomerID, pIsActive, pSearchTxt, pSkipNo, pTakeNo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.FetchDto> SkipNGetN_OfColorDataWithSearchAsync(int pCustomerID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo) {
            return base.Channel.SkipNGetN_OfColorDataWithSearchAsync(pCustomerID, pIsActive, pSearchTxt, pSkipNo, pTakeNo);
        }
        
        public Entities.GPMS.CatalogDto AddCarton(Entities.GPMS.CartonInfoBo pCartonInfoBo) {
            return base.Channel.AddCarton(pCartonInfoBo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> AddCartonAsync(Entities.GPMS.CartonInfoBo pCartonInfoBo) {
            return base.Channel.AddCartonAsync(pCartonInfoBo);
        }
        
        public Entities.GPMS.CatalogDto UpdateCarton(Entities.GPMS.CartonInfoBo pCartonInfoBo) {
            return base.Channel.UpdateCarton(pCartonInfoBo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> UpdateCartonAsync(Entities.GPMS.CartonInfoBo pCartonInfoBo) {
            return base.Channel.UpdateCartonAsync(pCartonInfoBo);
        }
        
        public Entities.GPMS.CatalogDto GetCartonById(int pCartonId) {
            return base.Channel.GetCartonById(pCartonId);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetCartonByIdAsync(int pCartonId) {
            return base.Channel.GetCartonByIdAsync(pCartonId);
        }
        
        public Entities.GPMS.CatalogDto GetCartonByCode(string pCartonCode) {
            return base.Channel.GetCartonByCode(pCartonCode);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetCartonByCodeAsync(string pCartonCode) {
            return base.Channel.GetCartonByCodeAsync(pCartonCode);
        }
        
        public Entities.GPMS.CatalogDto GetAllCartons(System.Nullable<bool> pIsActive) {
            return base.Channel.GetAllCartons(pIsActive);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetAllCartonsAsync(System.Nullable<bool> pIsActive) {
            return base.Channel.GetAllCartonsAsync(pIsActive);
        }
        
        public Entities.GPMS.CatalogDto AddColor(Entities.GPMS.ColorInfoBo pColorInfoBo) {
            return base.Channel.AddColor(pColorInfoBo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> AddColorAsync(Entities.GPMS.ColorInfoBo pColorInfoBo) {
            return base.Channel.AddColorAsync(pColorInfoBo);
        }
        
        public Entities.GPMS.CatalogDto UpdateColor(Entities.GPMS.ColorInfoBo pColorInfoBo) {
            return base.Channel.UpdateColor(pColorInfoBo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> UpdateColorAsync(Entities.GPMS.ColorInfoBo pColorInfoBo) {
            return base.Channel.UpdateColorAsync(pColorInfoBo);
        }
        
        public Entities.GPMS.CatalogDto GetColorById(int pColorId) {
            return base.Channel.GetColorById(pColorId);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetColorByIdAsync(int pColorId) {
            return base.Channel.GetColorByIdAsync(pColorId);
        }
        
        public Entities.GPMS.CatalogDto GetColorByCode(string pColorCode) {
            return base.Channel.GetColorByCode(pColorCode);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetColorByCodeAsync(string pColorCode) {
            return base.Channel.GetColorByCodeAsync(pColorCode);
        }
        
        public Entities.GPMS.CatalogDto GetAllColors(System.Nullable<bool> pIsActive) {
            return base.Channel.GetAllColors(pIsActive);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetAllColorsAsync(System.Nullable<bool> pIsActive) {
            return base.Channel.GetAllColorsAsync(pIsActive);
        }
        
        public Entities.GPMS.CatalogDto AddCustomer(Entities.GPMS.CustomerInfoBo pCustomerInfoBo) {
            return base.Channel.AddCustomer(pCustomerInfoBo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> AddCustomerAsync(Entities.GPMS.CustomerInfoBo pCustomerInfoBo) {
            return base.Channel.AddCustomerAsync(pCustomerInfoBo);
        }
        
        public Entities.GPMS.CatalogDto UpdateCustomer(Entities.GPMS.CustomerInfoBo pCustomerInfoBo) {
            return base.Channel.UpdateCustomer(pCustomerInfoBo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> UpdateCustomerAsync(Entities.GPMS.CustomerInfoBo pCustomerInfoBo) {
            return base.Channel.UpdateCustomerAsync(pCustomerInfoBo);
        }
        
        public Entities.GPMS.CatalogDto GetCustomerById(int pCustomerId) {
            return base.Channel.GetCustomerById(pCustomerId);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetCustomerByIdAsync(int pCustomerId) {
            return base.Channel.GetCustomerByIdAsync(pCustomerId);
        }
        
        public Entities.GPMS.CatalogDto GetCustomerByCode(string pCustomerCode) {
            return base.Channel.GetCustomerByCode(pCustomerCode);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetCustomerByCodeAsync(string pCustomerCode) {
            return base.Channel.GetCustomerByCodeAsync(pCustomerCode);
        }
        
        public Entities.GPMS.CatalogDto GetAllCustomers(System.Nullable<bool> pIsActive) {
            return base.Channel.GetAllCustomers(pIsActive);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetAllCustomersAsync(System.Nullable<bool> pIsActive) {
            return base.Channel.GetAllCustomersAsync(pIsActive);
        }
        
        public Entities.GPMS.CatalogDto AddPaymentMode(Entities.GPMS.PaymentModeInfoBo pPaymentModeInfoBo) {
            return base.Channel.AddPaymentMode(pPaymentModeInfoBo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> AddPaymentModeAsync(Entities.GPMS.PaymentModeInfoBo pPaymentModeInfoBo) {
            return base.Channel.AddPaymentModeAsync(pPaymentModeInfoBo);
        }
        
        public Entities.GPMS.CatalogDto UpdatePaymentMode(Entities.GPMS.PaymentModeInfoBo pPaymentModeInfoBo) {
            return base.Channel.UpdatePaymentMode(pPaymentModeInfoBo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> UpdatePaymentModeAsync(Entities.GPMS.PaymentModeInfoBo pPaymentModeInfoBo) {
            return base.Channel.UpdatePaymentModeAsync(pPaymentModeInfoBo);
        }
        
        public Entities.GPMS.CatalogDto GetPaymentModeById(int pPaymentModeId) {
            return base.Channel.GetPaymentModeById(pPaymentModeId);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetPaymentModeByIdAsync(int pPaymentModeId) {
            return base.Channel.GetPaymentModeByIdAsync(pPaymentModeId);
        }
        
        public Entities.GPMS.CatalogDto GetPaymentModeByCode(string pPaymentModeCode) {
            return base.Channel.GetPaymentModeByCode(pPaymentModeCode);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetPaymentModeByCodeAsync(string pPaymentModeCode) {
            return base.Channel.GetPaymentModeByCodeAsync(pPaymentModeCode);
        }
        
        public Entities.GPMS.CatalogDto GetAllPaymentModes(System.Nullable<bool> pIsActive) {
            return base.Channel.GetAllPaymentModes(pIsActive);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetAllPaymentModesAsync(System.Nullable<bool> pIsActive) {
            return base.Channel.GetAllPaymentModesAsync(pIsActive);
        }
        
        public Entities.GPMS.CatalogDto AddSize(Entities.GPMS.SizeInfoBo pSizeInfoBo) {
            return base.Channel.AddSize(pSizeInfoBo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> AddSizeAsync(Entities.GPMS.SizeInfoBo pSizeInfoBo) {
            return base.Channel.AddSizeAsync(pSizeInfoBo);
        }
        
        public Entities.GPMS.CatalogDto UpdateSize(Entities.GPMS.SizeInfoBo pSizeInfoBo) {
            return base.Channel.UpdateSize(pSizeInfoBo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> UpdateSizeAsync(Entities.GPMS.SizeInfoBo pSizeInfoBo) {
            return base.Channel.UpdateSizeAsync(pSizeInfoBo);
        }
        
        public Entities.GPMS.CatalogDto GetSizeById(int pSizeId) {
            return base.Channel.GetSizeById(pSizeId);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetSizeByIdAsync(int pSizeId) {
            return base.Channel.GetSizeByIdAsync(pSizeId);
        }
        
        public Entities.GPMS.CatalogDto GetSizeByCode(string pSizeCode) {
            return base.Channel.GetSizeByCode(pSizeCode);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetSizeByCodeAsync(string pSizeCode) {
            return base.Channel.GetSizeByCodeAsync(pSizeCode);
        }
        
        public Entities.GPMS.CatalogDto GetAllSizes(System.Nullable<bool> pIsActive) {
            return base.Channel.GetAllSizes(pIsActive);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetAllSizesAsync(System.Nullable<bool> pIsActive) {
            return base.Channel.GetAllSizesAsync(pIsActive);
        }
        
        public Entities.GPMS.CatalogDto AddStyle(Entities.GPMS.StyleInfoBo pStyleInfoBo) {
            return base.Channel.AddStyle(pStyleInfoBo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> AddStyleAsync(Entities.GPMS.StyleInfoBo pStyleInfoBo) {
            return base.Channel.AddStyleAsync(pStyleInfoBo);
        }
        
        public Entities.GPMS.CatalogDto UpdateStyle(Entities.GPMS.StyleInfoBo pStyleInfoBo) {
            return base.Channel.UpdateStyle(pStyleInfoBo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> UpdateStyleAsync(Entities.GPMS.StyleInfoBo pStyleInfoBo) {
            return base.Channel.UpdateStyleAsync(pStyleInfoBo);
        }
        
        public Entities.GPMS.CatalogDto GetStyleById(int pStyleId) {
            return base.Channel.GetStyleById(pStyleId);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetStyleByIdAsync(int pStyleId) {
            return base.Channel.GetStyleByIdAsync(pStyleId);
        }
        
        public Entities.GPMS.CatalogDto GetStyleByCode(string pStyleCode) {
            return base.Channel.GetStyleByCode(pStyleCode);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetStyleByCodeAsync(string pStyleCode) {
            return base.Channel.GetStyleByCodeAsync(pStyleCode);
        }
        
        public Entities.GPMS.CatalogDto GetAllStyles(System.Nullable<bool> pIsActive) {
            return base.Channel.GetAllStyles(pIsActive);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetAllStylesAsync(System.Nullable<bool> pIsActive) {
            return base.Channel.GetAllStylesAsync(pIsActive);
        }
        
        public Entities.GPMS.CatalogDto AddTerm(Entities.GPMS.TermInfoBo pTermInfoBo) {
            return base.Channel.AddTerm(pTermInfoBo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> AddTermAsync(Entities.GPMS.TermInfoBo pTermInfoBo) {
            return base.Channel.AddTermAsync(pTermInfoBo);
        }
        
        public Entities.GPMS.CatalogDto UpdateTerm(Entities.GPMS.TermInfoBo pTermInfoBo) {
            return base.Channel.UpdateTerm(pTermInfoBo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> UpdateTermAsync(Entities.GPMS.TermInfoBo pTermInfoBo) {
            return base.Channel.UpdateTermAsync(pTermInfoBo);
        }
        
        public Entities.GPMS.CatalogDto GetTermById(int pTermId) {
            return base.Channel.GetTermById(pTermId);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetTermByIdAsync(int pTermId) {
            return base.Channel.GetTermByIdAsync(pTermId);
        }
        
        public Entities.GPMS.CatalogDto GetTermByCode(string pTermCode) {
            return base.Channel.GetTermByCode(pTermCode);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetTermByCodeAsync(string pTermCode) {
            return base.Channel.GetTermByCodeAsync(pTermCode);
        }
        
        public Entities.GPMS.CatalogDto GetAllTerms(System.Nullable<bool> pIsActive) {
            return base.Channel.GetAllTerms(pIsActive);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetAllTermsAsync(System.Nullable<bool> pIsActive) {
            return base.Channel.GetAllTermsAsync(pIsActive);
        }
        
        public Entities.GPMS.CatalogDto GetPOTypeById(int pPOTypeId) {
            return base.Channel.GetPOTypeById(pPOTypeId);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetPOTypeByIdAsync(int pPOTypeId) {
            return base.Channel.GetPOTypeByIdAsync(pPOTypeId);
        }
        
        public Entities.GPMS.CatalogDto GetPOTypeByCode(string pPOTypeCode) {
            return base.Channel.GetPOTypeByCode(pPOTypeCode);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetPOTypeByCodeAsync(string pPOTypeCode) {
            return base.Channel.GetPOTypeByCodeAsync(pPOTypeCode);
        }
        
        public Entities.GPMS.CatalogDto GetAllPOTypes(System.Nullable<bool> pIsActive) {
            return base.Channel.GetAllPOTypes(pIsActive);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetAllPOTypesAsync(System.Nullable<bool> pIsActive) {
            return base.Channel.GetAllPOTypesAsync(pIsActive);
        }
        
        public Entities.GPMS.CatalogDto GetPOLevelById(int pPOLevelId) {
            return base.Channel.GetPOLevelById(pPOLevelId);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetPOLevelByIdAsync(int pPOLevelId) {
            return base.Channel.GetPOLevelByIdAsync(pPOLevelId);
        }
        
        public Entities.GPMS.CatalogDto GetPOLevelByCode(string pPOLevelCode) {
            return base.Channel.GetPOLevelByCode(pPOLevelCode);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetPOLevelByCodeAsync(string pPOLevelCode) {
            return base.Channel.GetPOLevelByCodeAsync(pPOLevelCode);
        }
        
        public Entities.GPMS.CatalogDto GetAllPOLevels(System.Nullable<bool> pIsActive) {
            return base.Channel.GetAllPOLevels(pIsActive);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetAllPOLevelsAsync(System.Nullable<bool> pIsActive) {
            return base.Channel.GetAllPOLevelsAsync(pIsActive);
        }
        
        public Entities.GPMS.CatalogDto GetPOFromById(int pPOFromId) {
            return base.Channel.GetPOFromById(pPOFromId);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetPOFromByIdAsync(int pPOFromId) {
            return base.Channel.GetPOFromByIdAsync(pPOFromId);
        }
        
        public Entities.GPMS.CatalogDto GetPOFromByCode(string pPOFromCode) {
            return base.Channel.GetPOFromByCode(pPOFromCode);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetPOFromByCodeAsync(string pPOFromCode) {
            return base.Channel.GetPOFromByCodeAsync(pPOFromCode);
        }
        
        public Entities.GPMS.CatalogDto GetAllPOFroms(System.Nullable<bool> pIsActive) {
            return base.Channel.GetAllPOFroms(pIsActive);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetAllPOFromsAsync(System.Nullable<bool> pIsActive) {
            return base.Channel.GetAllPOFromsAsync(pIsActive);
        }
        
        public Entities.GPMS.CatalogDto GetPackingTypeById(int pPackingTypeId) {
            return base.Channel.GetPackingTypeById(pPackingTypeId);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetPackingTypeByIdAsync(int pPackingTypeId) {
            return base.Channel.GetPackingTypeByIdAsync(pPackingTypeId);
        }
        
        public Entities.GPMS.CatalogDto GetPackingTypeByCode(string pPackingTypeCode) {
            return base.Channel.GetPackingTypeByCode(pPackingTypeCode);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetPackingTypeByCodeAsync(string pPackingTypeCode) {
            return base.Channel.GetPackingTypeByCodeAsync(pPackingTypeCode);
        }
        
        public Entities.GPMS.CatalogDto GetAllPackingTypes(System.Nullable<bool> pIsActive) {
            return base.Channel.GetAllPackingTypes(pIsActive);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetAllPackingTypesAsync(System.Nullable<bool> pIsActive) {
            return base.Channel.GetAllPackingTypesAsync(pIsActive);
        }
        
        public Entities.GPMS.CatalogDto GetShipmentTermById(int pShipmentTermId) {
            return base.Channel.GetShipmentTermById(pShipmentTermId);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetShipmentTermByIdAsync(int pShipmentTermId) {
            return base.Channel.GetShipmentTermByIdAsync(pShipmentTermId);
        }
        
        public Entities.GPMS.CatalogDto GetShipmentTermByCode(string pShipmentTermCode) {
            return base.Channel.GetShipmentTermByCode(pShipmentTermCode);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetShipmentTermByCodeAsync(string pShipmentTermCode) {
            return base.Channel.GetShipmentTermByCodeAsync(pShipmentTermCode);
        }
        
        public Entities.GPMS.CatalogDto GetAllShipmentTerms(System.Nullable<bool> pIsActive) {
            return base.Channel.GetAllShipmentTerms(pIsActive);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetAllShipmentTermsAsync(System.Nullable<bool> pIsActive) {
            return base.Channel.GetAllShipmentTermsAsync(pIsActive);
        }
        
        public Entities.GPMS.CatalogDto UpdateShippingMethod(Entities.GPMS.ShippingMethodBo pShippingMethodBo) {
            return base.Channel.UpdateShippingMethod(pShippingMethodBo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> UpdateShippingMethodAsync(Entities.GPMS.ShippingMethodBo pShippingMethodBo) {
            return base.Channel.UpdateShippingMethodAsync(pShippingMethodBo);
        }
        
        public Entities.GPMS.CatalogDto GetShippingMethodById(int pShippingMethodId) {
            return base.Channel.GetShippingMethodById(pShippingMethodId);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetShippingMethodByIdAsync(int pShippingMethodId) {
            return base.Channel.GetShippingMethodByIdAsync(pShippingMethodId);
        }
        
        public Entities.GPMS.CatalogDto GetShippingMethodByCode(string pShippingMethodCode) {
            return base.Channel.GetShippingMethodByCode(pShippingMethodCode);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetShippingMethodByCodeAsync(string pShippingMethodCode) {
            return base.Channel.GetShippingMethodByCodeAsync(pShippingMethodCode);
        }
        
        public Entities.GPMS.CatalogDto GetAllShippingMethods(System.Nullable<bool> pIsActive) {
            return base.Channel.GetAllShippingMethods(pIsActive);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.CatalogDto> GetAllShippingMethodsAsync(System.Nullable<bool> pIsActive) {
            return base.Channel.GetAllShippingMethodsAsync(pIsActive);
        }
        
        public Entities.GPMS.OrderDto AddPOM(Entities.GPMS.POMBo POMBo) {
            return base.Channel.AddPOM(POMBo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.OrderDto> AddPOMAsync(Entities.GPMS.POMBo POMBo) {
            return base.Channel.AddPOMAsync(POMBo);
        }
        
        public Entities.GPMS.OrderDto UpdatePOM(Entities.GPMS.POMBo POMBo) {
            return base.Channel.UpdatePOM(POMBo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.OrderDto> UpdatePOMAsync(Entities.GPMS.POMBo POMBo) {
            return base.Channel.UpdatePOMAsync(POMBo);
        }
        
        public Entities.GPMS.OrderDto GetPOMById(int pPOMId) {
            return base.Channel.GetPOMById(pPOMId);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.OrderDto> GetPOMByIdAsync(int pPOMId) {
            return base.Channel.GetPOMByIdAsync(pPOMId);
        }
        
        public Entities.GPMS.OrderDto GetPOByPONo(string pPONo) {
            return base.Channel.GetPOByPONo(pPONo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.OrderDto> GetPOByPONoAsync(string pPONo) {
            return base.Channel.GetPOByPONoAsync(pPONo);
        }
        
        public Entities.GPMS.OrderDto DeletePOM(int Id, int userId) {
            return base.Channel.DeletePOM(Id, userId);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.OrderDto> DeletePOMAsync(int Id, int userId) {
            return base.Channel.DeletePOMAsync(Id, userId);
        }
        
        public Entities.GPMS.OrderDto UpdatePOApprovedStatus(Entities.GPMS.POApprovalStatusBo POApprovalStatuBo) {
            return base.Channel.UpdatePOApprovedStatus(POApprovalStatuBo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.OrderDto> UpdatePOApprovedStatusAsync(Entities.GPMS.POApprovalStatusBo POApprovalStatuBo) {
            return base.Channel.UpdatePOApprovedStatusAsync(POApprovalStatuBo);
        }
        
        public Entities.GPMS.ValidationDto IsPONumberExist(string pPoNo) {
            return base.Channel.IsPONumberExist(pPoNo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.ValidationDto> IsPONumberExistAsync(string pPoNo) {
            return base.Channel.IsPONumberExistAsync(pPoNo);
        }
        
        public Entities.GPMS.OrderDto AddPOD(Entities.GPMS.PODBo[] PODBo) {
            return base.Channel.AddPOD(PODBo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.OrderDto> AddPODAsync(Entities.GPMS.PODBo[] PODBo) {
            return base.Channel.AddPODAsync(PODBo);
        }
        
        public Entities.GPMS.OrderDto UpdatePOD(Entities.GPMS.PODBo PODBo) {
            return base.Channel.UpdatePOD(PODBo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.OrderDto> UpdatePODAsync(Entities.GPMS.PODBo PODBo) {
            return base.Channel.UpdatePODAsync(PODBo);
        }
        
        public Entities.GPMS.OrderDto AddUpdatePOD(Entities.GPMS.PODBo[] PODBoList) {
            return base.Channel.AddUpdatePOD(PODBoList);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.OrderDto> AddUpdatePODAsync(Entities.GPMS.PODBo[] PODBoList) {
            return base.Channel.AddUpdatePODAsync(PODBoList);
        }
        
        public Entities.GPMS.OrderDto GetPODById(int pPODId) {
            return base.Channel.GetPODById(pPODId);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.OrderDto> GetPODByIdAsync(int pPODId) {
            return base.Channel.GetPODByIdAsync(pPODId);
        }
        
        public Entities.GPMS.OrderDto DeletePOD(int Id, int userId) {
            return base.Channel.DeletePOD(Id, userId);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.OrderDto> DeletePODAsync(int Id, int userId) {
            return base.Channel.DeletePODAsync(Id, userId);
        }
        
        public Entities.GPMS.OrderDto AddPOSizeD(Entities.GPMS.POSizeDBo[] POSizeDBoList) {
            return base.Channel.AddPOSizeD(POSizeDBoList);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.OrderDto> AddPOSizeDAsync(Entities.GPMS.POSizeDBo[] POSizeDBoList) {
            return base.Channel.AddPOSizeDAsync(POSizeDBoList);
        }
        
        public Entities.GPMS.OrderDto UpdatePOSizeD(Entities.GPMS.POSizeDBo POSizeDBo) {
            return base.Channel.UpdatePOSizeD(POSizeDBo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.OrderDto> UpdatePOSizeDAsync(Entities.GPMS.POSizeDBo POSizeDBo) {
            return base.Channel.UpdatePOSizeDAsync(POSizeDBo);
        }
        
        public Entities.GPMS.OrderDto GetPOSizeDById(int pPOSizeDId) {
            return base.Channel.GetPOSizeDById(pPOSizeDId);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.OrderDto> GetPOSizeDByIdAsync(int pPOSizeDId) {
            return base.Channel.GetPOSizeDByIdAsync(pPOSizeDId);
        }
        
        public Entities.GPMS.OrderDto AddUpdatePOSizeD(Entities.GPMS.POSizeDBo[] POSizeDBoList) {
            return base.Channel.AddUpdatePOSizeD(POSizeDBoList);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.OrderDto> AddUpdatePOSizeDAsync(Entities.GPMS.POSizeDBo[] POSizeDBoList) {
            return base.Channel.AddUpdatePOSizeDAsync(POSizeDBoList);
        }
        
        public Entities.GPMS.OrderDto DeletePOSizeD(int Id, int userId) {
            return base.Channel.DeletePOSizeD(Id, userId);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.OrderDto> DeletePOSizeDAsync(int Id, int userId) {
            return base.Channel.DeletePOSizeDAsync(Id, userId);
        }
        
        public Entities.GPMS.OrderDto DeletePOSizeDCollection(int[] pPOSizeDIDs, int userId) {
            return base.Channel.DeletePOSizeDCollection(pPOSizeDIDs, userId);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.OrderDto> DeletePOSizeDCollectionAsync(int[] pPOSizeDIDs, int userId) {
            return base.Channel.DeletePOSizeDCollectionAsync(pPOSizeDIDs, userId);
        }
        
        public Entities.GPMS.ValidationDto IsItemExistInPO(string PONo, string ItemNo) {
            return base.Channel.IsItemExistInPO(PONo, ItemNo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.ValidationDto> IsItemExistInPOAsync(string PONo, string ItemNo) {
            return base.Channel.IsItemExistInPOAsync(PONo, ItemNo);
        }
        
        public Entities.GPMS.ValidationDto IsPackQtyValid(int pCustomerID, string PONo, string ItemNo, int CurrentPackQty) {
            return base.Channel.IsPackQtyValid(pCustomerID, PONo, ItemNo, CurrentPackQty);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.ValidationDto> IsPackQtyValidAsync(int pCustomerID, string PONo, string ItemNo, int CurrentPackQty) {
            return base.Channel.IsPackQtyValidAsync(pCustomerID, PONo, ItemNo, CurrentPackQty);
        }
        
        public Entities.GPMS.OrderDto GetItemNo(int pCustomerID, int pStyleID, int pColorID, int pSizeID) {
            return base.Channel.GetItemNo(pCustomerID, pStyleID, pColorID, pSizeID);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.OrderDto> GetItemNoAsync(int pCustomerID, int pStyleID, int pColorID, int pSizeID) {
            return base.Channel.GetItemNoAsync(pCustomerID, pStyleID, pColorID, pSizeID);
        }
        
        public Entities.GPMS.PackingDto AddPackingPlanData(Entities.GPMS.PackingDto PackingDto) {
            return base.Channel.AddPackingPlanData(PackingDto);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.PackingDto> AddPackingPlanDataAsync(Entities.GPMS.PackingDto PackingDto) {
            return base.Channel.AddPackingPlanDataAsync(PackingDto);
        }
        
        public Entities.GPMS.ValidationDto IsPackingPlanAlreadyProcessed(string pFileName) {
            return base.Channel.IsPackingPlanAlreadyProcessed(pFileName);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.ValidationDto> IsPackingPlanAlreadyProcessedAsync(string pFileName) {
            return base.Channel.IsPackingPlanAlreadyProcessedAsync(pFileName);
        }
        
        public Entities.GPMS.PackingDto AddPackingInstructionM(Entities.GPMS.PackingInstructionMBo packingInstructionMBo) {
            return base.Channel.AddPackingInstructionM(packingInstructionMBo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.PackingDto> AddPackingInstructionMAsync(Entities.GPMS.PackingInstructionMBo packingInstructionMBo) {
            return base.Channel.AddPackingInstructionMAsync(packingInstructionMBo);
        }
        
        public Entities.GPMS.PackingDto GetBoxDataByBarcode(string pBoxBacode) {
            return base.Channel.GetBoxDataByBarcode(pBoxBacode);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.PackingDto> GetBoxDataByBarcodeAsync(string pBoxBacode) {
            return base.Channel.GetBoxDataByBarcodeAsync(pBoxBacode);
        }
        
        public Entities.GPMS.PackingDto SaveBoxPacking(int pPackingInstructionMID, int pUpdatedByID, string pUpdatedBy) {
            return base.Channel.SaveBoxPacking(pPackingInstructionMID, pUpdatedByID, pUpdatedBy);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.PackingDto> SaveBoxPackingAsync(int pPackingInstructionMID, int pUpdatedByID, string pUpdatedBy) {
            return base.Channel.SaveBoxPackingAsync(pPackingInstructionMID, pUpdatedByID, pUpdatedBy);
        }
    }
}
