//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.GPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppActionGroupAccess
    {
        public int ID { get; set; }
        public int AppActionGroupID { get; set; }
        public int AppFormActionID { get; set; }
        public bool Status { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string Notes { get; set; }
    
        public virtual AppActionGroup AppActionGroup { get; set; }
        public virtual AppFormAction AppFormAction { get; set; }
    }
}
