//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.GPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppFormAction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppFormAction()
        {
            this.AppActionGroupAccesses = new HashSet<AppActionGroupAccess>();
        }
    
        public int ID { get; set; }
        public string FormActionNo { get; set; }
        public string FormActionName { get; set; }
        public string ControlName { get; set; }
        public string FormTitle { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string FormBehaviour { get; set; }
        public string ParentControl { get; set; }
        public string ControlType { get; set; }
        public string Action { get; set; }
        public string Description { get; set; }
        public bool Status { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppActionGroupAccess> AppActionGroupAccesses { get; set; }
    }
}
