//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.GPMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GPMSEntities : DbContext
    {
        public GPMSEntities()
            : base("name=GPMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppActionGroup> AppActionGroups { get; set; }
        public virtual DbSet<AppActionGroupAccess> AppActionGroupAccesses { get; set; }
        public virtual DbSet<AppFormAction> AppFormActions { get; set; }
        public virtual DbSet<AppMenu> AppMenus { get; set; }
        public virtual DbSet<AppMenuGroup> AppMenuGroups { get; set; }
        public virtual DbSet<AppMenuGroupAccess> AppMenuGroupAccesses { get; set; }
        public virtual DbSet<AppUserCompanyAccess> AppUserCompanyAccesses { get; set; }
        public virtual DbSet<CartonInfo> CartonInfoes { get; set; }
        public virtual DbSet<ColorInfo> ColorInfoes { get; set; }
        public virtual DbSet<CompanyInfo> CompanyInfoes { get; set; }
        public virtual DbSet<CustomerInfo> CustomerInfoes { get; set; }
        public virtual DbSet<PackingInstructionD> PackingInstructionDs { get; set; }
        public virtual DbSet<PackingInstructionM> PackingInstructionMs { get; set; }
        public virtual DbSet<PackingPlanData> PackingPlanDatas { get; set; }
        public virtual DbSet<PackingType> PackingTypes { get; set; }
        public virtual DbSet<PaymentModeInfo> PaymentModeInfoes { get; set; }
        public virtual DbSet<POD> PODs { get; set; }
        public virtual DbSet<POForm> POForms { get; set; }
        public virtual DbSet<POLevel> POLevels { get; set; }
        public virtual DbSet<POM> POMs { get; set; }
        public virtual DbSet<POSizeD> POSizeDs { get; set; }
        public virtual DbSet<POType> POTypes { get; set; }
        public virtual DbSet<ShipmentTerm> ShipmentTerms { get; set; }
        public virtual DbSet<ShippingMethod> ShippingMethods { get; set; }
        public virtual DbSet<SizeInfo> SizeInfoes { get; set; }
        public virtual DbSet<StyleInfo> StyleInfoes { get; set; }
        public virtual DbSet<TermInfo> TermInfoes { get; set; }
        public virtual DbSet<UOM> UOMs { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
    }
}
