//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.GPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackingInstructionD
    {
        public int ID { get; set; }
        public int PackingInstructionMID { get; set; }
        public string ItemNo { get; set; }
        public string UPC { get; set; }
        public int UOMID { get; set; }
        public string Color { get; set; }
        public string Style { get; set; }
        public string Size { get; set; }
        public Nullable<int> SizePackPCsQty { get; set; }
        public string SequenceNo { get; set; }
        public string StoreNo { get; set; }
        public string DC { get; set; }
        public Nullable<System.DateTime> ScanDate { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> UpdatedCount { get; set; }
        public string Notes { get; set; }
    }
}
