//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.GPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class POD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POD()
        {
            this.POSizeDs = new HashSet<POSizeD>();
        }

        public int ID { get; set; }
        public int POMID { get; set; }
        public int StyleID { get; set; }
        public int ColorID { get; set; }
        public Nullable<int> ComboCode { get; set; }
        public Nullable<bool> IsPilotRun { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> UpdatedCount { get; set; }
        public string Notes { get; set; }

        public ColorInfo ColorInfo { get; set; }
        public POM POM { get; set; }
        public StyleInfo StyleInfo { get; set; }
        public ICollection<POSizeD> POSizeDs { get; set; }
    }
}
