//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.GPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class POM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POM()
        {
            this.PODs = new HashSet<POD>();
        }
    
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public string PONo { get; set; }
        public string OriginalPONo { get; set; }
        public System.DateTime POReceivedDate { get; set; }
        public int PaymentModeID { get; set; }
        public int TermID { get; set; }
        public int ShippingMethodID { get; set; }
        public int ShipmentTermID { get; set; }
        public int POFormID { get; set; }
        public int POTypeID { get; set; }
        public int POLevelID { get; set; }
        public int PackingTypeID { get; set; }
        public Nullable<System.DateTime> POStartDate { get; set; }
        public string POStatus { get; set; }
        public string GarmentDescription { get; set; }
        public string BillTo { get; set; }
        public string Season { get; set; }
        public Nullable<int> RivisionNo { get; set; }
        public Nullable<System.DateTime> LastRevisionDate { get; set; }
        public string ClosingDate { get; set; }
        public string ClosedBy { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<System.DateTime> ShipRequestDate { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> UpdatedCount { get; set; }
        public string Notes { get; set; }
    
        public  CustomerInfo CustomerInfo { get; set; }
        public  PackingType PackingType { get; set; }
        public  PaymentModeInfo PaymentModeInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<POD> PODs { get; set; }
        public  POForm POForm { get; set; }
        public  POLevel POLevel { get; set; }
        public  POType POType { get; set; }
        public  ShipmentTerm ShipmentTerm { get; set; }
        public  ShippingMethod ShippingMethod { get; set; }
        public  TermInfo TermInfo { get; set; }
    }
}
