//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL.GPMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSizeD
    {
        public int ID { get; set; }
        public int PODID { get; set; }
        public int ColorID { get; set; }
        public int SizeID { get; set; }
        public int Qty { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<int> UpdatedCount { get; set; }
        public string Notes { get; set; }
    
        public virtual ColorInfo ColorInfo { get; set; }
        public virtual POD POD { get; set; }
        public virtual SizeInfo SizeInfo { get; set; }
    }
}
