//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP.GPMS.GPMSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GPMSService.IGPMSService")]
    public interface IGPMSService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/SkipNGetN_OfCustomerDataWithSearch", ReplyAction="http://tempuri.org/IGPMSService/SkipNGetN_OfCustomerDataWithSearchResponse")]
        Entities.GPMS.FetchDto SkipNGetN_OfCustomerDataWithSearch(int pCompanyID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/SkipNGetN_OfCustomerDataWithSearch", ReplyAction="http://tempuri.org/IGPMSService/SkipNGetN_OfCustomerDataWithSearchResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.FetchDto> SkipNGetN_OfCustomerDataWithSearchAsync(int pCompanyID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/SkipNGetN_OfStyleDataWithSearch", ReplyAction="http://tempuri.org/IGPMSService/SkipNGetN_OfStyleDataWithSearchResponse")]
        Entities.GPMS.FetchDto SkipNGetN_OfStyleDataWithSearch(int pCustomerID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/SkipNGetN_OfStyleDataWithSearch", ReplyAction="http://tempuri.org/IGPMSService/SkipNGetN_OfStyleDataWithSearchResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.FetchDto> SkipNGetN_OfStyleDataWithSearchAsync(int pCustomerID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/SkipNGetN_OfSizeDataWithSearch", ReplyAction="http://tempuri.org/IGPMSService/SkipNGetN_OfSizeDataWithSearchResponse")]
        Entities.GPMS.FetchDto SkipNGetN_OfSizeDataWithSearch(int pCustomerID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/SkipNGetN_OfSizeDataWithSearch", ReplyAction="http://tempuri.org/IGPMSService/SkipNGetN_OfSizeDataWithSearchResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.FetchDto> SkipNGetN_OfSizeDataWithSearchAsync(int pCustomerID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/SkipNGetN_OfColorDataWithSearch", ReplyAction="http://tempuri.org/IGPMSService/SkipNGetN_OfColorDataWithSearchResponse")]
        Entities.GPMS.FetchDto SkipNGetN_OfColorDataWithSearch(int pCustomerID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPMSService/SkipNGetN_OfColorDataWithSearch", ReplyAction="http://tempuri.org/IGPMSService/SkipNGetN_OfColorDataWithSearchResponse")]
        System.Threading.Tasks.Task<Entities.GPMS.FetchDto> SkipNGetN_OfColorDataWithSearchAsync(int pCustomerID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGPMSServiceChannel : APP.GPMS.GPMSService.IGPMSService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GPMSServiceClient : System.ServiceModel.ClientBase<APP.GPMS.GPMSService.IGPMSService>, APP.GPMS.GPMSService.IGPMSService {
        
        public GPMSServiceClient() {
        }
        
        public GPMSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GPMSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GPMSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GPMSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Entities.GPMS.FetchDto SkipNGetN_OfCustomerDataWithSearch(int pCompanyID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo) {
            return base.Channel.SkipNGetN_OfCustomerDataWithSearch(pCompanyID, pIsActive, pSearchTxt, pSkipNo, pTakeNo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.FetchDto> SkipNGetN_OfCustomerDataWithSearchAsync(int pCompanyID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo) {
            return base.Channel.SkipNGetN_OfCustomerDataWithSearchAsync(pCompanyID, pIsActive, pSearchTxt, pSkipNo, pTakeNo);
        }
        
        public Entities.GPMS.FetchDto SkipNGetN_OfStyleDataWithSearch(int pCustomerID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo) {
            return base.Channel.SkipNGetN_OfStyleDataWithSearch(pCustomerID, pIsActive, pSearchTxt, pSkipNo, pTakeNo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.FetchDto> SkipNGetN_OfStyleDataWithSearchAsync(int pCustomerID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo) {
            return base.Channel.SkipNGetN_OfStyleDataWithSearchAsync(pCustomerID, pIsActive, pSearchTxt, pSkipNo, pTakeNo);
        }
        
        public Entities.GPMS.FetchDto SkipNGetN_OfSizeDataWithSearch(int pCustomerID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo) {
            return base.Channel.SkipNGetN_OfSizeDataWithSearch(pCustomerID, pIsActive, pSearchTxt, pSkipNo, pTakeNo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.FetchDto> SkipNGetN_OfSizeDataWithSearchAsync(int pCustomerID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo) {
            return base.Channel.SkipNGetN_OfSizeDataWithSearchAsync(pCustomerID, pIsActive, pSearchTxt, pSkipNo, pTakeNo);
        }
        
        public Entities.GPMS.FetchDto SkipNGetN_OfColorDataWithSearch(int pCustomerID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo) {
            return base.Channel.SkipNGetN_OfColorDataWithSearch(pCustomerID, pIsActive, pSearchTxt, pSkipNo, pTakeNo);
        }
        
        public System.Threading.Tasks.Task<Entities.GPMS.FetchDto> SkipNGetN_OfColorDataWithSearchAsync(int pCustomerID, System.Nullable<bool> pIsActive, string pSearchTxt, int pSkipNo, System.Nullable<int> pTakeNo) {
            return base.Channel.SkipNGetN_OfColorDataWithSearchAsync(pCustomerID, pIsActive, pSearchTxt, pSkipNo, pTakeNo);
        }
    }
}
